### ISSUE TITLE
cannot install

### ISSUE THREAD

**Issue by masterkain** [einzige/sneaky-save#15]
getting

```
fatal: no submodule mapping found in .gitmodules for path 'spec/integrations'

Retrying `git submodule deinit --all` due to error (2/4): Bundler::Source::Git::GitCommandError Git error: command `git submodule deinit --all` in directory /Users/kain/.rvm/gems/ruby-2.3.1/bundler/gems/sneaky-save-03866e838f62 has failed.
If this error persists you could try removing the cache directory '/Users/kain/.rvm/gems/ruby-2.3.1/cache/bundler/git/sneaky-save-13cb906327c60ce788e3f1db6c01a34c2097daef'fatal: no submodule mapping found in .gitmodules for path 'spec/integrations'
```

**Comment by einzige** [comment]
Hi @masterkain what git version do you have?

**Comment by alexander-mayr** [comment]
+1 here

**Comment by einzige** [comment]
@alexander-mayr maybe I ever did fastforward push, not sure. Does cleaning your cache directory resolve the problem?

`If this error persists you could try removing the cache directory '/Users/kain/.rvm/gems/ruby-2.3.1/cache/bundler/git/sneaky-save-13cb906327c60ce788e3f1db6c01a34c2097daef'fatal: no submodule mapping found in .gitmodules for path 'spec/integrations'
`

**Comment by harz87** [comment]
+1 here
git version: git version 2.10.1 (Apple Git-78)
and deleting the cache directory didn't solve it either

**Comment by einzige** [comment]
@harz87 @alexander-mayr @masterkain the fix is here: https://github.com/ravensnowbird/sneaky-save/commit/d3a005c4d263090d5df6b5163625af21dae48a10 I hope @ravensnowbird will submit his PR soon :) If not, I will.

**Comment by einzige** [comment]
Bumped 0.1.2, closing
